"""fix models

Revision ID: 3ff3aa0e279e
Revises: cbc6a56d7076
Create Date: 2026-03-01 20:46:21.553329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ff3aa0e279e'
down_revision: Union[str, Sequence[str], None] = 'cbc6a56d7076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'public_id')
    op.drop_column('customers', 'updated_at')
    op.drop_column('customers', 'is_deleted')
    op.drop_column('debts', 'public_id')
    op.drop_column('debts', 'updated_at')
    op.drop_column('debts', 'is_deleted')
    op.drop_column('payments', 'public_id')
    op.drop_column('payments', 'updated_at')
    op.drop_column('payments', 'is_deleted')
    op.drop_column('subscriptions', 'public_id')
    op.drop_column('subscriptions', 'updated_at')
    op.drop_column('users', 'public_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=True))
    op.add_column('debts', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('debts', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('debts', sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
