"""add notifications table

Revision ID: 43a652713952
Revises: da3e9336515f
Create Date: 2026-03-04 23:48:07.515822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43a652713952'
down_revision: Union[str, Sequence[str], None] = 'da3e9336515f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=True)
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
