"""add soft delete

Revision ID: 4c1e494ae038
Revises: 173d8c7a845b
Create Date: 2026-02-13 08:01:49.406303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c1e494ae038'
down_revision: Union[str, Sequence[str], None] = '173d8c7a845b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('debts', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debts', 'is_active')
    op.drop_column('customers', 'is_active')
    # ### end Alembic commands ###
