"""add payment_date to payments

Revision ID: 6bdb0579b489
Revises: 3ff3aa0e279e
Create Date: 2026-03-04 12:00:00.774728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bdb0579b489'
down_revision: Union[str, Sequence[str], None] = '3ff3aa0e279e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payment_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'payment_date')
    # ### end Alembic commands ###
